# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faverrequest',
            name='issuer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='faver_app.FaverUser'),
        ),
    ]
