# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0004_remove_faveruser_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='FaverContract',
        ),
    ]
