# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0005_auto_20170122_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='faveruser',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
