# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0006_faveruser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='faveruser',
            name='coins',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='faveruser',
            name='reputation',
            field=models.IntegerField(default=10),
        ),
    ]
