# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0008_auto_20170122_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='faverrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=43.663, max_digits=6),
        ),
        migrations.AddField(
            model_name='faverrequest',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=-79.396, max_digits=6),
        ),
    ]
