# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faver_app', '0009_auto_20170122_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='favercontract',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
